name: Deploy to ecellmedicaps.com

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Set CI to false
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Build project
        run: npm run build
        env:
          CI: false

      - name: Deploy to GitHub Pages
        run: |
          git push
